### ISSUE TITLE
Why the preference window is blank?

### ISSUE THREAD

**Issue by RoadToDream** [Ulauncher/Ulauncher#114]
![image](https://cloud.githubusercontent.com/assets/8088354/25001567/a662f80e-2078-11e7-9f97-c19bbc6aafbd.png)
As it is...
How to fix it? 

---

:warning: **WORKAROUND** :warning: 
Run ulauncher with this env var `WEBKIT_DISABLE_COMPOSITING_MODE=1 ulauncher`
or update the desktop file (usually located in /usr/share/applications) like this:
```
Exec=env WEBKIT_DISABLE_COMPOSITING_MODE=1 /usr/bin/ulauncher --hide-window
```

In future versions, we'll try to get rid of WebKit completely.

**Comment by RoadToDream** [comment]
Don't know why it has fixed after i installed the dev version and failed ...

**Comment by gornostal** [comment]
Hi @RoadToDream 
So does it work now?
If not, could you run the app from console `ulauncher -v`, open preferences, and then post console output here?

**Comment by gornostal** [comment]
I also need to know your OS and desktop environment (Gnome, KDE, etc)

**Comment by ydawei** [comment]
Same here. Gnome 3.22.0, Ubuntu 17.04, Ulauncher version: at commit ccde34978765274484282ac57b54fdca09b519d8.

**Comment by gornostal** [comment]
@ydawei could you post `ulauncher -v` output?

You have to close the app first.

**Comment by RoadToDream** [comment]
It has fixed after I reinstalled it. 
I am using a Ubuntu 16.04 with Gnome.

**Comment by ydawei** [comment]
There is too much output. I post here the error message when opening the preference window.
The complete output is attached as a file:
[ulauncher_output.txt](https://github.com/Ulauncher/Ulauncher/files/935624/ulauncher_output.txt)

FYI, I installed ulauncher multiple times.

```CONSOLE ERROR Not allowed to load local resource: file:///home/ydawei/Downloads/Ulauncher/data/preferences/build/fonts/glyphicons-halflings-regular.woff2
CONSOLE ERROR Not allowed to load local resource: file:///home/ydawei/Downloads/Ulauncher/data/preferences/build/fonts/glyphicons-halflings-regular.woff
CONSOLE ERROR Not allowed to load local resource: file:///home/ydawei/Downloads/Ulauncher/data/preferences/build/fonts/glyphicons-halflings-regular.ttf
CONSOLE ERROR Not allowed to load local resource: file:///home/ydawei/Downloads/Ulauncher/data/preferences/build/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular
CONSOLE ERROR Not allowed to load local resource: file:///home/ydawei/Downloads/Ulauncher/data/preferences/build/css/ui-grid.woff
CONSOLE ERROR Not allowed to load local resource: file:///home/ydawei/Downloads/Ulauncher/data/preferences/build/css/ui-grid.ttf
CONSOLE ERROR Not allowed to load local resource: file:///home/ydawei/Downloads/Ulauncher/data/preferences/build/css/ui-grid.svg?#ui-grid
file:///home/ydawei/Downloads/Ulauncher/data/preferences/build/js/app.min.js:1797:36: CONSOLE ERROR TypeError: d.module("ngRoute",[]).info is not a function. (In 'd.module("ngRoute",[]).info({angularVersion:"1.6.4"})', 'd.module("ngRoute",[]).info' is undefined)
file:///home/ydawei/Downloads/Ulauncher/data/preferences/build/js/app.min.js:39:48: CONSOLE ERROR Error: [$injector:modulerr] http://errors.angularjs.org/1.4.14/$injector/modulerr?p0=ulauncher&p1=%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.4.14%2F%24injector%2Fnomod%3Fp0%3Dulauncher%0Afile%3A%2F%2F%2Fhome%2Fydawei%2FDownloads%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A6%3A422%0Afile%3A%2F%2F%2Fhome%2Fydawei%2FDownloads%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A24%3A187%0Ab%40file%3A%2F%2F%2Fhome%2Fydawei%2FDownloads%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A23%3A252%0Afile%3A%2F%2F%2Fhome%2Fydawei%2FDownloads%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A38%3A239%0Ap%40file%3A%2F%2F%2Fhome%2Fydawei%2FDownloads%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A7%3A359%0Ag%40file%3A%2F%2F%2Fhome%2Fydawei%2FDownloads%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A38%3A86%0Adb%40file%3A%2F%2F%2Fhome%2Fydawei%2FDownloads%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A41%3A369%0Ac%40file%3A%2F%2F%2Fhome%2Fydawei%2FDownloads%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A19%3A465%0Ade%40file%3A%2F%2F%2Fhome%2Fydawei%2FDownloads%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A19%3A84%0Afile%3A%2F%2F%2Fhome%2Fydawei%2FDownloads%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A299%3A476%0Ab%40file%3A%2F%2F%2Fhome%2Fydawei%2FDownloads%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A178%3A160%0APf%40file%3A%2F%2F%2Fhome%2Fydawei%2FDownloads%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A35%3A481%0Ad%40file%3A%2F%2F%2Fhome%2Fydawei%2FDownloads%2FUlauncher%2Fdata%2Fpreferences%2Fbuild%2Fjs%2Fapp.min.js%3A35%3A425
CONSOLE ERROR Not allowed to load local resource: file:///home/ydawei/Downloads/Ulauncher/data/preferences/build/fonts/glyphicons-halflings-regular.woff2
CONSOLE ERROR Not allowed to load local resource: file:///home/ydawei/Downloads/Ulauncher/data/preferences/build/fonts/glyphicons-halflings-regular.woff
CONSOLE ERROR Not allowed to load local resource: file:///home/ydawei/Downloads/Ulauncher/data/preferences/build/fonts/glyphicons-halflings-regular.ttf
CONSOLE ERROR Not allowed to load local resource: file:///home/ydawei/Downloads/Ulauncher/data/preferences/build/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular
CONSOLE ERROR Not allowed to load local resource: file:///home/ydawei/Downloads/Ulauncher/data/preferences/build/css/ui-grid.woff
CONSOLE ERROR Not allowed to load local resource: file:///home/ydawei/Downloads/Ulauncher/data/preferences/build/css/ui-grid.ttf
CONSOLE ERROR Not allowed to load local resource: file:///home/ydawei/Downloads/Ulauncher/data/preferences/build/css/ui-grid.svg?#ui-grid

**Comment by xircon** [comment]
The ulauncher AUR version functions as expected, the ulauncher-git version has the blank preferences.
Manjaro Linux, unstable branch, i3wm/KDE both the same.  Away from my computer, can post output later.

**Comment by gornostal** [comment]
@ydawei how did you install Ulauncher?
You've got it installed to ~/Downloads, which is weird.
If you installed it from source did you follow these steps? https://github.com/Ulauncher/Ulauncher#build-and-run

**Comment by gornostal** [comment]
I think I found the root cause. It only reproduces when installed from source.

**Comment by gornostal** [comment]
Fixed in [v2.2.0](https://github.com/Ulauncher/Ulauncher/releases/tag/2.2.0.r1)

**Comment by seagle0128** [comment]
This issue still exists on Linux Mint 19. No error in `ulauncher -v`.

![image](https://user-images.githubusercontent.com/140797/48774523-7d715980-ed05-11e8-8f28-3d9c5bdcdad8.png)

**Comment by tchrisdyer** [comment]
I'm having the same issue on Linux Mint 19.1. Ulauncher seems to work fine, but each time I click the settings button a white window appears for a moment with the message "Loading" then becomes transparent and just hangs.

I ran the `ulauncher -v` command and received the following warnings:

```
/usr/lib/python2.7/dist-packages/ulauncher/util/desktop/notification.py:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:6: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, Gtk, WebKit2, GLib
```

**Comment by mattarroz** [comment]
I've got the same issue.

**Steps to reproduce:**
1. Start ulauncher --verbose
2. Open Preferences window

**Ulauncher version**: Tried v4.4.0.r1 and v5.3.0~beta1 (deb sourced from homepage)
**Linux distro**: Debian 9
**Desktop environment**: Tried Mate 1.16 and 1.20 

**Logs**:
https://gist.github.com/mattarroz/b179b5952633c5b107c75dbdd3e5b52f

**Comment by kyoh86** [comment]
I've got the same issue.

**Linux distro**: Arch
**Desktop environment**: Gnome 3.34.2

<details><summary>logs:</summary>
<pre>2020-01-30 23:07:08,091 | INFO | ulauncher: main() | Ulauncher version 5.6.1
2020-01-30 23:07:08,091 | INFO | ulauncher: main() | Extension API version 2.0.0
2020-01-30 23:07:08,091 | INFO | ulauncher: main() | GTK+ 3.24.13
2020-01-30 23:07:08,091 | INFO | ulauncher: main() | Is Wayland: True
2020-01-30 23:07:08,091 | INFO | ulauncher: main() | Wayland compatibility: off
2020-01-30 23:07:08,176 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'input-box'
2020-01-30 23:07:08,178 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','destroy', 'on_destroy'
2020-01-30 23:07:08,178 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event'
2020-01-30 23:07:08,178 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event'
2020-01-30 23:07:08,179 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'input','key_press_event', 'on_input_key_press_event'
2020-01-30 23:07:08,179 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_input_changed'
2020-01-30 23:07:08,179 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_about_activate'
2020-01-30 23:07:08,179 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_close_activate'
2020-01-30 23:07:08,179 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_preferences_activate'
2020-01-30 23:07:08,179 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_preferences_dialog_destroyed'
2020-01-30 23:07:08,181 | DEBUG | ulauncher.utils.display: get_screens() | Found 1 monitor(s)
2020-01-30 23:07:08,182 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2020-01-30 23:07:08,192 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2020-01-30 23:07:08,194 | INFO | ulauncher.api.server.ExtensionServer: _start_thread() | Starting WS server on port 5054
2020-01-30 23:07:08,194 | INFO | ulauncher.search.apps.app_watcher: start() | Started scanning desktop dirs
2020-01-30 23:07:08,204 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 48 apps in cache
2020-01-30 23:07:08,204 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/evolution-calendar.desktop": constructor returned NULL
2020-01-30 23:07:08,205 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/gcr-viewer.desktop": constructor returned NULL
2020-01-30 23:07:08,209 | INFO | ulauncher.ui.windows.UlauncherWindow: bind_show_app_hotkey() | Trying to bind app hotkey: <Primary>space
2020-01-30 23:07:08,220 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 55 apps in the system
2020-01-30 23:07:08,220 | INFO | ulauncher.search.apps.app_watcher: start() | Scanned desktop dirs in 0.03 seconds
2020-01-30 23:07:08,224 | DEBUG | ulauncher.search.apps.app_watcher: start() | Start watching desktop files...
2020-01-30 23:07:22,633 | DEBUG | ulauncher.utils.display: get_screens() | Found 1 monitor(s)
2020-01-30 23:07:22,633 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2020-01-30 23:07:22,633 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2020-01-30 23:07:27,793 | DEBUG | ulauncher.ui.windows.UlauncherWindow: activate_preferences() | create new preferences_dialog
2020-01-30 23:07:27,806 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_hotkey_set'
2020-01-30 23:07:27,806 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_scheme_callback'
2020-01-30 23:07:27,875 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'hotkey-dialog-vbox1'
2020-01-30 23:07:27,876 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'new-hotkey-label'
2020-01-30 23:07:27,879 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_dialog','delete_event', 'on_delete_event'
2020-01-30 23:07:27,880 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_input','key_press_event', 'on_hotkey_input_key_press_event'
2020-01-30 23:07:28,184 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_get_all() | API call /get/all
2020-01-30 23:09:16,448 | DEBUG | ulauncher.ui.windows.UlauncherWindow: on_preferences_dialog_destroyed() | on_preferences_dialog_destroyed
2020-01-30 23:09:33,647 | DEBUG | ulauncher.utils.display: get_screens() | Found 1 monitor(s)
2020-01-30 23:09:33,647 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2020-01-30 23:09:33,648 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2020-01-30 23:09:36,614 | DEBUG | ulauncher.ui.windows.UlauncherWindow: activate_preferences() | create new preferences_dialog
2020-01-30 23:09:36,624 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_hotkey_set'
2020-01-30 23:09:36,624 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_scheme_callback'
2020-01-30 23:09:36,630 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'hotkey-dialog-vbox1'
2020-01-30 23:09:36,630 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'new-hotkey-label'
2020-01-30 23:09:36,632 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_dialog','delete_event', 'on_delete_event'
2020-01-30 23:09:36,633 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_input','key_press_event', 'on_hotkey_input_key_press_event'
2020-01-30 23:09:36,885 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_get_all() | API call /get/all
2020-01-30 23:09:49,937 | DEBUG | ulauncher.utils.display: get_screens() | Found 1 monitor(s)
2020-01-30 23:09:49,937 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2020-01-30 23:09:49,938 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2020-01-30 23:09:54,314 | DEBUG | ulauncher.ui.windows.UlauncherWindow: activate_preferences() | show existing preferences_dialog
2020-01-30 23:10:10,795 | DEBUG | ulauncher.ui.windows.UlauncherWindow: on_preferences_dialog_destroyed() | on_preferences_dialog_destroyed
2020-01-30 23:19:02,021 | DEBUG | ulauncher.utils.display: get_screens() | Found 1 monitor(s)
2020-01-30 23:19:02,021 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2020-01-30 23:19:02,021 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2020-01-30 23:19:08,276 | DEBUG | ulauncher.ui.windows.UlauncherWindow: activate_preferences() | create new preferences_dialog
2020-01-30 23:19:08,280 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_hotkey_set'
2020-01-30 23:19:08,280 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_scheme_callback'
2020-01-30 23:19:08,285 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'hotkey-dialog-vbox1'
2020-01-30 23:19:08,285 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'new-hotkey-label'
2020-01-30 23:19:08,287 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_dialog','delete_event', 'on_delete_event'
2020-01-30 23:19:08,288 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_input','key_press_event', 'on_hotkey_input_key_press_event'
2020-01-30 23:19:08,613 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_get_all() | API call /get/all
2020-01-30 23:19:44,422 | DEBUG | ulauncher.ui.windows.UlauncherWindow: on_preferences_dialog_destroyed() | on_preferences_dialog_destroyed
2020-01-30 23:19:46,969 | DEBUG | ulauncher.utils.display: get_screens() | Found 1 monitor(s)
2020-01-30 23:19:46,969 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2020-01-30 23:19:46,970 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2020-01-30 23:19:50,675 | DEBUG | ulauncher.ui.windows.UlauncherWindow: activate_preferences() | create new preferences_dialog
2020-01-30 23:19:50,687 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_hotkey_set'
2020-01-30 23:19:50,687 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_scheme_callback'
2020-01-30 23:19:50,693 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'hotkey-dialog-vbox1'
2020-01-30 23:19:50,693 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'new-hotkey-label'
2020-01-30 23:19:50,695 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_dialog','delete_event', 'on_delete_event'
2020-01-30 23:19:50,696 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_input','key_press_event', 'on_hotkey_input_key_press_event'
2020-01-30 23:19:51,006 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_get_all() | API call /get/all
2020-01-30 23:20:41,236 | DEBUG | ulauncher.ui.windows.UlauncherWindow: on_preferences_dialog_destroyed() | on_preferences_dialog_destroyed</pre></details>

**Comment by LeartS** [comment]
Same problem on Ubuntu 19.10 on Wayland, [ulauncher_5.6.1_all.deb](https://github.com/Ulauncher/Ulauncher/releases/download/5.6.1/ulauncher_5.6.1_all.deb) downloaded from the website, no errors in logs.

**Comment by seagle0128** [comment]
It's daed ...

**Comment by bwoodruff** [comment]
Preferences doesn't open for me either.

<details><summary>ulauncher -v:</summary>
```
2020-03-07 13:51:22,647 | INFO | ulauncher: main() | Ulauncher version 5.7.0~beta2
2020-03-07 13:51:22,647 | INFO | ulauncher: main() | Extension API version 2.0.0
2020-03-07 13:51:22,647 | INFO | ulauncher: main() | GTK+ 3.24.13
2020-03-07 13:51:22,647 | INFO | ulauncher: main() | Is Wayland: True
2020-03-07 13:51:22,647 | INFO | ulauncher: main() | Wayland compatibility: off
2020-03-07 13:51:22,657 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'input-box'
2020-03-07 13:51:22,659 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','destroy', 'on_destroy'
2020-03-07 13:51:22,659 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event'
2020-03-07 13:51:22,659 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event'
2020-03-07 13:51:22,660 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'input','key_press_event', 'on_input_key_press_event'
2020-03-07 13:51:22,660 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_input_changed'
2020-03-07 13:51:22,661 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_about_activate'
2020-03-07 13:51:22,661 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_close_activate'
2020-03-07 13:51:22,661 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_preferences_activate'
2020-03-07 13:51:22,661 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_preferences_dialog_destroyed'
2020-03-07 13:51:22,662 | DEBUG | ulauncher.utils.display: get_screens() | Found 1 monitor(s)
2020-03-07 13:51:22,662 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2020-03-07 13:51:22,668 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2020-03-07 13:51:22,669 | INFO | ulauncher.api.server.ExtensionServer: _start_thread() | Starting WS server on port 5054
2020-03-07 13:51:22,669 | INFO | ulauncher.search.apps.app_watcher: start() | Started scanning desktop dirs
2020-03-07 13:51:22,678 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 43 apps in cache
2020-03-07 13:51:22,685 | INFO | ulauncher.utils.desktop.reader: read_desktop_file() | Could not read "/usr/share/applications/evolution-calendar.desktop": constructor returned NULL
2020-03-07 13:51:22,695 | INFO | ulauncher.ui.windows.UlauncherWindow: bind_show_app_hotkey() | Trying to bind app hotkey: <Primary>space
2020-03-07 13:51:22,697 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 43 apps in the system
2020-03-07 13:51:22,697 | INFO | ulauncher.search.apps.app_watcher: start() | Scanned desktop dirs in 0.03 seconds
2020-03-07 13:51:22,701 | DEBUG | ulauncher.search.apps.app_watcher: start() | Start watching desktop files...
2020-03-07 13:51:31,308 | DEBUG | ulauncher.ui.windows.UlauncherWindow: activate_preferences() | create new preferences_dialog
2020-03-07 13:51:31,318 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_hotkey_set'
2020-03-07 13:51:31,319 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_scheme_callback'
2020-03-07 13:51:31,379 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'hotkey-dialog-vbox1'
2020-03-07 13:51:31,380 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'new-hotkey-label'
2020-03-07 13:51:31,382 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_dialog','delete_event', 'on_delete_event'
2020-03-07 13:51:31,383 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_input','key_press_event', 'on_hotkey_input_key_press_event'
2020-03-07 13:51:31,615 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_get_all() | API call /get/all
```
</details>

* Fedora 31
* Gnome 3.34.4
* ulauncher ulauncher_5.7.0.beta2_fedora.rpm
(also tried ulauncher_5.7.0_fedora.rpm)

![Screenshot from 2020-03-07 14-01-33](https://user-images.githubusercontent.com/553522/76150845-831abc00-607c-11ea-9610-c8d67fa05c9b.png)
![Screenshot from 2020-03-07 14-01-40](https://user-images.githubusercontent.com/553522/76150849-84e47f80-607c-11ea-9204-b69cfeccdd00.png)

**Comment by gornostal** [comment]
I once again tried on several distros in VBox including Fedora 31 with the latest updates, but could not reproduce this issue.

I guess some package interferes with probably WebkitGtk and it makes Ulaundher preferences crash unexpectedly. 
No solution yet :(

**Comment by theonlydoo** [comment]
I had the exact same issue with meaningless logs while using the verbose output. I managed to install and configure extensions by using a X11 session. Is there any way to provide you with some meaningful debugging output?

**Comment by dashorty** [comment]
same issue here

- GNOME Shell 3.36.0
- Linux archxps 5.5.9-arch1-2 #1 SMP PREEMPT Thu, 12 Mar 2020 23:01:33 +0000 x86_64 GNU/Linux
- aur/ulauncher-git DEV-1 (same with aur/ulauncher 5.7.0-1)

> ulauncher -v 

```
                    [!]
        Looks like you are in Wayland session
        Please run Ulauncher with env var
        GDK_BACKEND set to 'x11' like this:

        GDK_BACKEND=x11 ulauncher

```
> GDK_BACKEND=x11 ulauncher -v
```

2020-03-16 13:13:58,931 | INFO | ulauncher: main() | Ulauncher version DEV
2020-03-16 13:13:58,932 | INFO | ulauncher: main() | Extension API version 2.0.0
2020-03-16 13:13:58,932 | INFO | ulauncher: main() | GTK+ 3.24.14
2020-03-16 13:13:58,932 | INFO | ulauncher: main() | Is Wayland: True
2020-03-16 13:13:58,932 | INFO | ulauncher: main() | Wayland compatibility: off
2020-03-16 13:13:58,940 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'input-box'
2020-03-16 13:13:58,942 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','destroy', 'on_destroy'
2020-03-16 13:13:58,942 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event'
2020-03-16 13:13:58,942 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event'
2020-03-16 13:13:58,943 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'input','key_press_event', 'on_input_key_press_event'
2020-03-16 13:13:58,943 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_input_changed'
2020-03-16 13:13:58,943 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_about_activate'
2020-03-16 13:13:58,943 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_close_activate'
2020-03-16 13:13:58,943 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_preferences_activate'
2020-03-16 13:13:58,943 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_preferences_dialog_destroyed'
2020-03-16 13:13:58,945 | DEBUG | ulauncher.utils.display: get_screens() | Found 1 monitor(s)
2020-03-16 13:13:58,945 | DEBUG | ulauncher.utils.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2020-03-16 13:13:58,960 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2020-03-16 13:13:58,962 | INFO | ulauncher.api.server.ExtensionServer: _start_thread() | Starting WS server on port 5054
2020-03-16 13:13:58,962 | INFO | ulauncher.search.apps.app_watcher: start() | Started scanning desktop dirs
2020-03-16 13:13:58,987 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 85 apps in cache
2020-03-16 13:13:59,001 | INFO | ulauncher.ui.windows.UlauncherWindow: bind_show_app_hotkey() | Trying to bind app hotkey: <Primary>space
2020-03-16 13:13:59,033 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 85 apps in the system
2020-03-16 13:13:59,034 | INFO | ulauncher.search.apps.app_watcher: start() | Scanned desktop dirs in 0.07 seconds
2020-03-16 13:13:59,041 | DEBUG | ulauncher.search.apps.app_watcher: start() | Start watching desktop files...

(ulauncher:17702): Gdk-CRITICAL **: 13:13:59.117: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
2020-03-16 13:14:03,711 | DEBUG | ulauncher.ui.windows.UlauncherWindow: activate_preferences() | create new preferences_dialog
2020-03-16 13:14:03,723 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_hotkey_set'
2020-03-16 13:14:03,724 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_scheme_callback'
2020-03-16 13:14:03,829 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'hotkey-dialog-vbox1'
2020-03-16 13:14:03,829 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'new-hotkey-label'
2020-03-16 13:14:03,834 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_dialog','delete_event', 'on_delete_event'
2020-03-16 13:14:03,835 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_input','key_press_event', 'on_hotkey_input_key_press_event'
2020-03-16 13:14:04,328 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_get_all() | API call /get/all
2020-03-16 13:14:07,744 | DEBUG | ulauncher.ui.windows.UlauncherWindow: on_preferences_dialog_destroyed() | on_preferences_dialog_destroyed

```

![ulauncher](https://user-images.githubusercontent.com/2131900/76761648-1a27f800-6790-11ea-8b15-6b4ba779fb3f.png)
![ulauncher_pref](https://user-images.githubusercontent.com/2131900/76761768-4e9bb400-6790-11ea-9f61-376038b2408c.png)

**Comment by stevesong** [comment]
Same problem.  Arch Linux, Gnome 3.36, Wayland

The following output on opening preferences window:

```
2020-03-28 22:15:13,147 | DEBUG | ulauncher.ui.windows.UlauncherWindow: activate_preferences() | create new preferences_dialog
2020-03-28 22:15:13,170 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_hotkey_set'
2020-03-28 22:15:13,170 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_scheme_callback'
2020-03-28 22:15:13,238 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'hotkey-dialog-vbox1'
2020-03-28 22:15:13,239 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'new-hotkey-label'
2020-03-28 22:15:13,242 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_dialog','delete_event', 'on_delete_event'
2020-03-28 22:15:13,243 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_input','key_press_event', 'on_hotkey_input_key_press_event'
2020-03-28 22:15:13,537 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_get_all() | API call /get/all

```

**Comment by darkowic** [comment]
I have the same issue.
Version:
```
$ ulauncher --version
Gtk-Message: 09:51:18.133: Failed to load module "appmenu-gtk-module"
ulauncher 5.7.4
```
System: Pop OS
Gnome:
```
$ gnome-shell --version

** (process:9019): WARNING **: 09:52:11.872: Failed to set RT scheduler: Operation not permitted
GNOME Shell 3.34.3
```


Stacktrace when opening preferences:
```
2020-04-15 09:49:42,312 | DEBUG | ulauncher.ui.windows.UlauncherWindow: activate_preferences() | create new preferences_dialog
2020-04-15 09:49:42,336 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_hotkey_set'
2020-04-15 09:49:42,336 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_scheme_callback'
2020-04-15 09:49:42,378 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'hotkey-dialog-vbox1'
2020-04-15 09:49:42,378 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'new-hotkey-label'
2020-04-15 09:49:42,380 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_dialog','delete_event', 'on_delete_event'
2020-04-15 09:49:42,381 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_input','key_press_event', 'on_hotkey_input_key_press_event'
Gtk-Message: 09:49:42.388: Failed to load module "appmenu-gtk-module"
2020-04-15 09:49:42,635 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_get_all() | API call /get/all

(WebKitWebProcess:8671): Gdk-ERROR **: 09:49:42.771: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 209 error_code 2 request_code 151 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

**Comment by petre2dor** [comment]
same issue here

**Comment by CollinAlpert** [comment]
Same problem with me: I get the critical error `gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed`

**Comment by madalinoprea** [comment]
Had the same issue on Ubuntu 20.04 LTS, Gnome 3.36.2, Wayland and instructions mentioned in https://wiki.archlinux.org/index.php/Wayland#Qt_5 fixed the issue.

```
QT_QPA_PLATFORM=wayland  ulauncher
```

**Comment by theonlydoo** [comment]
indeed, it works pretty fine combined w/ https://github.com/Ulauncher/Ulauncher/wiki/Hotkey-In-Wayland

**Comment by stevesong** [comment]
> `QT_QPA_PLATFORM=wayland ulauncher`

So are you launching it that way without GDK_BACKEND=x11 as well because if I just use the QT env variable, I get the message:
        Looks like you are in Wayland session
        Please run Ulauncher with env var
        GDK_BACKEND set to 'x11' like this:

        GDK_BACKEND=x11 ulauncher

**Comment by vasiauvi** [comment]
I also get the Preferences window as blank on this setup:
OS: Ubuntu 20.04 focal
Kernel: x86_64 Linux 5.4.0-33-generic
DE: GNOME 3.36.2

`
2020-05-30 21:59:22,382 | INFO | ulauncher.utils.desktop.reader: find_apps_cached() | Found 148 apps in the system
2020-05-30 21:59:22,382 | INFO | ulauncher.search.apps.app_watcher: start() | Scanned desktop dirs in 0.12 seconds
2020-05-30 21:59:22,391 | DEBUG | ulauncher.search.apps.app_watcher: start() | Start watching desktop files...
2020-05-30 21:59:25,867 | DEBUG | ulauncher.ui.windows.UlauncherWindow: activate_preferences() | create new preferences_dialog
2020-05-30 21:59:25,891 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_hotkey_set'
2020-05-30 21:59:25,891 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_scheme_callback'
2020-05-30 21:59:25,953 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'hotkey-dialog-vbox1'
2020-05-30 21:59:25,953 | DEBUG | ulauncher.ui.windows.Builder: __init__() | consider using a pythonic name instead of design name 'new-hotkey-label'
2020-05-30 21:59:25,960 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_dialog','delete_event', 'on_delete_event'
2020-05-30 21:59:25,963 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'hotkey_input','key_press_event', 'on_hotkey_input_key_press_event'
2020-05-30 21:59:26,465 | INFO | ulauncher.ui.windows.PreferencesUlauncherDialog: prefs_get_all() | API call /get/all
2020-05-30 21:59:56,374 | DEBUG | ulauncher.ui.windows.UlauncherWindow: on_preferences_dialog_destroyed() | on_preferences_dialog_destroyed
`

**Comment by gitbobbed** [comment]
Just a heads-up that in Fedora Workstation 32 I was getting the same error, but only when ulauncher was launched with the GDK_BACKEND=x11 environment variable (figured that out because it never happened when I launched ulauncher from terminal). Once I removed env GDK_BACKEND=x11 from the .desktop files (in /usr/share/applications and ~/.config/autostart), ulauncher settings open normally however I open it. Continues to work fine on Wayland and X.Org as well.

**Comment by stevesong** [comment]
@gitbobbed that is curious.  When I run ulauncher from the terminal, it fails with the following message:
```
                    [!]
        Looks like you are in Wayland session
        Please run Ulauncher with env var
        GDK_BACKEND set to 'x11' like this:

        GDK_BACKEND=x11 ulauncher
```
Arch linux 5.6.15-arch1-1  Are you sure it works with Wayland?

**Comment by FedeCuci** [comment]
I'm having the same issue here on Ubuntu Wayland 20.04 running GNOME 3.36.2. I am quite sure that it is a Wayland specific issue as I was on X11 just a few days ago and never encountered this problem. 

I don't know if anybody else is experiencing this but when I click on the blank preferences window, it actually becomes transparent. I am still able to click on any button on the window btw, it's just that it is all transparent.

**Comment by vasiauvi** [comment]
@FedeCuci no, I am on X11 (seen by echo $XDG_SESSION_TYPE).

**Comment by FedeCuci** [comment]
You're right, didn't see that...

**Comment by JoJk0** [comment]
Same issue on fresh install of Ubuntu 20.04 on X11

**Comment by seagle0128** [comment]
OMG, over three years for this issue.

**Comment by theonlydoo** [comment]
> OMG, over three years for this issue.

feel free to open a PR and solve it by yourself. 
Meanwhile, there is a workaround in this thread.

**Comment by JoJk0** [comment]
> > OMG, over three years for this issue.
> 
> feel free to open a PR and solve it by yourself.
> Meanwhile, there is a workaround in this thread.

Not for me as switching to X11 doesn't help

**Comment by metalstorm161** [comment]
I am also facing the same issue, tried the solution from @gitbobbed and it worked. But now ULauncher pops up in the upper left corner instead of the center, so turned on the 'Center New Windows' option under Windows section in Gnome Tweaks.

**Comment by gornostal** [comment]
If someone could create a VBox image where I can reproduce the issue, I'll try to fix it.

**Comment by FedeCuci** [comment]
Tried creating several Ubuntu 20.04 VM's, but it seems to be working fine both on Wayland and X11... At this point I'm not sure what to do.

**Comment by metalstorm161** [comment]
I tried reproducing it in VMs too, but it works just fine there. 

For what it's worth, here's the log from my machine: [ulauncher_log.txt](https://github.com/Ulauncher/Ulauncher/files/4821680/ulauncher_log.txt)

**Comment by mattlenz** [comment]
I've been experiencing this issue too with GNOME on archlinux.

The fix for me is starting ulauncher this way;

```
WEBKIT_DISABLE_COMPOSITING_MODE=1 ulauncher
```

**Comment by gornostal** [comment]
Can someone else confirm that the workaround posted above works? :arrow_up: 
Then I'll add it to the description while we are looking for a permanent fix.

@mattlenz thanks for sharing  :+1:

**Comment by stevesong** [comment]
Can confirm the fix from @mattlenz works on Arch Linux.  Full line in ulauncher.desktop is

`Exec=env WEBKIT_DISABLE_COMPOSITING_MODE=1 GDK_BACKEND=x11 /usr/bin/ulauncher --hide-window`

A big thank you to @mattlenz as this has been bugging me for a long time.

**Comment by FedeCuci** [comment]
I can also confirm that when starting Ulauncher the way @mattlenz proposed I am also able to view the preferences, thanks!.

**Comment by metalstorm161** [comment]
Confirmed working on Fedora 32 as well.

**Comment by vasiauvi** [comment]
Confirmed that works also in Ubuntu 20.04. Thanks @mattlenz and @gornostal.

**Comment by praneetk96** [comment]
> Confirmed working on Fedora 32 as well.

Can you share the steps for this solution on Fedora, i am also using Fedora 32 Gnome, i am new to linux!

**Comment by praneetk96** [comment]
> Confirmed working on Fedora 32 as well.

i also use Fedora 32, actually not a professional on linux ecosystem, but i am learning things in linux, i've just found a thread on Github about Ulauncher Settings not opening, i am also in the same position not able to fix it, brother can you share the steps to solve this problem as we both use same OS and same App launcher "Ulauncher".

**Comment by pgqz53** [comment]
Update:
Looks like the previous workaround is no longer necessary. On gnome + wayland, simply removing all of the additional env variables will make it work. Basically `Exec=/usr/bin/ulauncher --hide-window`. Tested on Fedora 32 + gnome 3.36.4 on wayland.

**Comment by pgqz53** [comment]
I have not tested this on other wayland combinations, would be great if someone could test this on plasma wayland and maybe sway as well. If this solution works outside of gnome, maybe we can consider dropping the env variables in the desktop file for good.

**Comment by Muosvr** [comment]
> Update:
> Looks like the previous workaround is no longer necessary. On gnome + wayland, simply removing all of the additional env variables will make it work. Basically `Exec=/usr/bin/ulauncher --hide-window`. Tested on Fedora 32 + gnome 3.36.4 on wayland, running ulauncher 5.8.

That works for me to show preference, but the launcher window is no longer centered.

**Comment by pgqz53** [comment]
> That works for me to show preference, but the launcher window is no longer centered.

I used `gsettings set org.gnome.mutter center-new-windows true` to work around this.

**Comment by RemizZ** [comment]
Just came across this issue on Pop OS 20.07. How is this fixed exactly? The output I get when opening the preferences:
`(WebKitWebProcess:182742): Gdk-ERROR **: 15:24:18.101: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 210 error_code 2 request_code 151 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)`

**Comment by av1m** [comment]
Hello, same issue on Fedora 33
`Exec=env WEBKIT_DISABLE_COMPOSITING_MODE=1 /usr/bin/ulauncher --hide-window` don't work.
I managed to open the settings window only once using the Terminal (by spamming ulauncher)

**Comment by stephane-klein** [comment]
If I remove `env GDK_BACKEND=x11` in `usr/share/applications/ulauncher.desktop`, so with this content:

```
[Desktop Entry]
Name=Ulauncher
Comment=Application launcher for Linux
Categories=GNOME;Utility;
Exec=/usr/bin/ulauncher --hide-window
Icon=ulauncher
Terminal=false
Type=Application
```

All works perfecly on:

- Ubuntu 20.10
- Gnome / Wayland
- Intel GFX drivers

Question: what do you think to update this file? https://github.com/Ulauncher/Ulauncher/blob/4833e779332ac1a439e3fce1f96af684214683b8/ulauncher.desktop.in

**Comment by jacksongoode** [comment]
Is there any followup for this issue? This appears like a pretty huge bug for generic users on Wayland.

**Comment by a42niem** [comment]
being on debian with xfce4 and using  version 5.12.2
adding WEBKIT_DISABLE_COMPOSITING_MODE=1 made the window visible  
some dbus-warnings are gone adding also NO_AT_BRIDGE=1

**Comment by Programie** [comment]
I have the same issue on KDE running on Ubuntu 21.10.

Previously, I used Cinnamon on Ubuntu 21.10 in which case, Ulauncher just worked fine as expected. But since I switched to KDE, the preferences window is always empty.

I was able trace down the issue: It is caused by the WebKit implementation of the used GTK library. Whenever a local URL (file:///some/path) is opened, a "load-failed" event is triggered with "WebKitPolicyError: Frame load interrupted (102)" as the error message.

I used the following example script (replace `file:///home/programie/Desktop/test.html` with the file URL to any text file):

```python
import sys

import gi
gi.require_version('Gtk', '3.0')
gi.require_version('WebKit2', '4.0')

from gi.repository import Gtk, WebKit2

class Browser(Gtk.Window):
    def __init__(self, *args, **kwargs):
        super(Browser, self).__init__(*args, **kwargs)

        self.webview = WebKit2.WebView()
        self.webview.connect('load-failed', print)
        self.show()

        scrolled_window = Gtk.ScrolledWindow()
        scrolled_window.add(self.webview)

        scrolled_window.show_all()

        self.add(scrolled_window)

        settings = self.webview.get_settings()
        settings.set_allow_file_access_from_file_urls(True)
        settings.set_allow_universal_access_from_file_urls(True)
        settings.set_enable_write_console_messages_to_stdout(True)
        self.webview.load_uri("file:///home/programie/Desktop/test.html")

if __name__ == "__main__":
    Gtk.init(sys.argv)

    browser = Browser()

    Gtk.main()
```

So, I guess it's not an issue with Ulauncher but the WebKit implementation of GTK?

**Comment by FinnHering** [comment]
Foremost, thank you for your efforts to try to fix this issue!

I have good and bad news!

Let's start with the bad news (it's shorter, lol):
Your commits basically didn't fix this issue at all. It had not that much to do with the 'protocol' (file:// vs http://). It was about the local HTML file type. I tried it with local .txt files, and they were served just fine.

<hr>

So now to the good news: 
I might have found the solution. This is actually really weird. I would've never thought about that. I found this: https://stackoverflow.com/questions/71734719/webkitgtk-doesnt-load-local-files

The gist: 
It has something to do with your mime database.
If you want to fix this specific issue, you basically have to run: 
```bash
rm ~/.local/share/mime/packages/user-extension-html.xml
update-mime-database ~/.local/share/mime
```
So far, this fixed it on all of my machines, both running Arch Linux. _Both ulauncher and ulauncher-git work_

Before I did the update, I created a full backup of the 'broken' mime folder. If anyone wants to elaborate further, I've attached it as a zip archive here: [mime.zip](https://github.com/Ulauncher/Ulauncher/files/8484915/mime.zip).

@friday Perhaps you should write about this in the troubleshooting section.

**Comment by friday** [comment]
[5.14.4](https://github.com/Ulauncher/Ulauncher/releases/tag/5.14.4) should fix this issue for some (see #1001 for more info), but I think it won't for those who were able to solve this with `WEBKIT_DISABLE_COMPOSITING_MODE=1`

**Comment by Danila-hub** [comment]
It doesn't work for me. Maybe I did something wrong?
![Screenshot from 2022-07-31 20-45-48](https://user-images.githubusercontent.com/55277394/182038875-dd73fc6e-77be-486d-be7a-25f831315420.png)

**Comment by friday** [comment]
> It doesn't work for me. Maybe I did something wrong?

You have two `Exec`. Only the last one counts.

**Comment by friday** [comment]
Also, I highly suggest to start by copying the desktop entry to your home dir:

```sh
cp /usr/share/applications/ulauncher.desktop ~/.local/share/applications/
```

Then modify `~/.local/share/applications/ulauncher.desktop`

Files in `/usr/share/applications` belong to packages. Modifications will be undone when you upgrade or reinstall the them. So you should copy them first (like above). For more info on Ulauncher and desktop entries see https://github.com/Ulauncher/Ulauncher/discussions/991#user-content-invalid-entries

(I should add this issue to the troubleshooting also, but I wasn't sure it still happened)

**Comment by Thanatermesis** [comment]
preferences needs to be build:

> make prefs

before to "make install" it

**Comment by friday** [comment]
In preparations of Ulauncher v6 stable I'm going through the issue tracker. This issue is already fixed in v6 by rewriting the implementation completely (no web view). It has likely been filly fixed in v5 too because we disabled hardware rendering.

If you still have issue sin v5, you can switch to dev-release https://ulauncher.io/#Download or wait for v6 stable.
