### ISSUE TITLE
Ulauncher doesn't work in Wayland

### ISSUE THREAD

**Issue by gornostal** [Ulauncher/Ulauncher#157]
TODO:
* Wrap Keybinder calls in try-catch
* Find out if there are calls that make the app crash in Wayland
* Update Preferences to show a message that the user has to manually set app hot key via system preferences

**Comment by gornostal** [comment]
Fixed in dev release 3.3.0.r0

**Comment by jzuijlek** [comment]
I still get a segmentation fault in Ubuntu 17.10 with 3.3.0.rc0.

```
$ ulauncher -v
/usr/lib/python2.7/dist-packages/ulauncher/util/desktop/notification.py:1: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/dist-packages/ulauncher/ui/windows/PreferencesUlauncherDialog.py:6: PyGIWarning: WebKit2 was imported without specifying a version first. Use gi.require_version('WebKit2', '4.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gio, Gtk, WebKit2, GLib
2017-12-19 21:46:11,925 | INFO | ulauncher: main() | Ulauncher version 3.3.0.r0
2017-12-19 21:46:11,925 | INFO | ulauncher: main() | GTK+ 3.22.25
2017-12-19 21:46:11,966 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','destroy', 'on_destroy'
2017-12-19 21:46:11,967 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_in_event', 'on_focus_in_event'
2017-12-19 21:46:11,967 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'ulauncher_window','focus_out_event', 'on_focus_out_event'
2017-12-19 21:46:11,968 | DEBUG | ulauncher.ui.windows.Builder: do_connect() | connect builder by name 'input','key_press_event', 'on_input_key_press_event'
2017-12-19 21:46:11,968 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_about_activate'
2017-12-19 21:46:11,969 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_preferences_dialog_destroyed'
2017-12-19 21:46:11,969 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_close_activate'
2017-12-19 21:46:11,969 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_mnu_preferences_activate'
2017-12-19 21:46:11,969 | DEBUG | ulauncher.ui.windows.Builder: log_unconnected_functions() | Not connected to builder 'on_input_changed'
2017-12-19 21:46:11,970 | DEBUG | ulauncher.util.display: get_screens() | Found 1 monitor(s).
2017-12-19 21:46:11,970 | DEBUG | ulauncher.util.display: get_screens() |   Monitor 0 - X: 0, Y: 0, W: 1920, H: 1080
2017-12-19 21:46:11,973 | DEBUG | ulauncher.ui.windows.UlauncherWindow: show_results() | render 0 results
2017-12-19 21:46:11,974 | INFO | ulauncher.api.server.ExtensionServer: _start_thread() | Starting WS server on port 5050
2017-12-19 21:46:12,012 | INFO | ulauncher.ui.windows.UlauncherWindow: bind_show_app_hotkey() | Trying to bind app hotkey: <Primary>space
[1]    6160 segmentation fault (core dumped)  ulauncher -v
```

**Comment by gornostal** [comment]
@jzuijlek thanks for the logs. I'll try to reproduce the issue over the weekends and hopefully fix it. I'll let you know about the results

**Comment by noam09** [comment]
@jzuijlek, do you also get the error if you try assigning a hotkey that doesn't include `<Primary>`, `<Super>` or `<Space>`? For example `<Alt> + g`.
In my case, combinations using `<Super>` have to be pressed multiple times to work. I just use `<Alt>` instead.

**Comment by gornostal** [comment]
@jzuijlek there are still a few issues with running Ulauncher in Wayland

1. You have to run it with `GDK_BACKEND=x11` env var. When you run the app from Ubuntu Activities launcher, it will run it correctly because that env var is in the .desktop file. If you'd like to start the app from command line you can do that like this: `$ GDK_BACKEND=x11 ulauncher -v`
2. App hotkey doesn't work while some apps are in focus. For example, if you open the terminal app and then press <kbd>Ctrl</kbd> <kbd>Space</kbd> nothing will happen. But if you press the hotkey while Firefox or is active, it will work

I'm going to look for a way to resolve these two.

**Comment by gornostal** [comment]
Done in v4

**Comment by dannykopping** [comment]
Experiencing this issue on Ubuntu 16.04.4 running XFCE4

**Comment by gornostal** [comment]
Hi @dannykopping 
Could you open a new issue please? So we don't spam people in this one?
