### ISSUE TITLE
Plugins not working: Websocket error "x takes exactly n arguments (n-1 given)"

### ISSUE THREAD

**Issue by friday** [Ulauncher/Ulauncher#275]
**Steps to reproduce:**
1. Start Ulauncher
2. With the kill plugin installed type in `kill firefox` (or something else you don't mind killing if the plugin should work)

Result: Nothing (no tab completion and nothing happens on pressing enter). Only "Loading" is shown. 

The same thing happens with all the plugins I've tried (npms, search files, myip)

Every time I try I get a websocket error in "ulauncher.api.client.Client.Client" that "on_message() takes exactly 3 arguments (2 given)" and sometimes "on_open() takes exactly 2 arguments (1 given)" (see log for more details).

**Ulauncher version**: 4.1.0.r1
**Linux distro**: Arch
**Desktop environment**: Gnome/GTK with x11
**Python version**: 2.7.15 (GCC 8.1.1 20180531)

[Verbose log](https://gist.github.com/friday/93cabd91dba83b4769c375f44ce3b8fc)

----

**Fix: update python-websocket-client (python2-websocket-client for Arch and Fedora) to version 0.52 or higher.**

**Comment by friday** [comment]
I dug around a bit and think it's likely related to this issue: https://github.com/websocket-client/websocket-client/issues/467

**Comment by bondzula** [comment]
I'm having the same issue and the fix works as well.

**Comment by houbaron** [comment]
Yep, I meet it, too.
```
2018-08-28 10:47:58,933 | DEBUG | ulauncher.api.server.ExtensionController: _send_event() | Send event KeywordQueryEvent to "com.github.brpaz.ulauncher-hash"
com.github.brpaz.ulauncher-hash | 2018-08-28 10:47:59,004 | ERROR | websocket: error() | error from callback <bound method Client.on_message of <ulauncher.api.client.Client.Client object at 0x7fcb131ed890>>: on_message() takes exactly 3 arguments (2 given)
  File "/usr/lib/python2.7/site-packages/websocket/_app.py", line 333, in _callback
    callback(*args)
```

**Comment by CRAG666** [comment]
sigo teniendo el mismo error 2018-09-02 15:45:11,048 | ERROR | websocket: error() | error from callback <bound method Client.on_message of <ulauncher.api.client.Client.Client object at 0x7fab6e8cec90>>: on_message() takes exactly 3 arguments (2 given)

**Comment by gioulisapo** [comment]
I get the same error as well. 
`com.github.manulaiko.ulauncher-openinbrowser | 2018-09-03 10:57:02,225 | ERROR | websocket: error() | error from callback <bound method Client.on_message of <ulauncher.api.client.Client.Client object at 0x7fe69db51910>>: on_message() takes exactly 3 arguments (2 given)`

**Comment by friday** [comment]
No need to paste the error. We know this is unfixed and because of websocket-client/websocket-client#467

**Comment by friday** [comment]
0.51.0 is also broken. You probably meant 0.52.0, which was released just a day or so before you wrote that comment. Anyway the latest version works again, so this is fixed now :+1: Since you kept the issue open I'll let you be the judge of when to close it.

**Comment by gornostal** [comment]
Thanks for the heads up.

I'm going to close it in a few weeks. By that time people will hopefully upgrade their packages and won't run into this issues.

**Comment by flick36** [comment]
0.53 is also broken? cause i'm getting the same error and i have 0.53 installed

**Comment by friday** [comment]
Yup. Seems like he gave up and reverted the version which was working for Ulauncher in favor of a version that didn't break other usage cases. Very confusing.

**Comment by flick36** [comment]
> Yup. Seems like he gave up and reverted the version which was working for Ulauncher in favor of a version that didn't break other usage cases. Very confusing.

Sorry I delete my comment, cause i indeed found your comment, on the commit, that reverted the functionality :sweat_smile: so, what's next?

**Comment by friday** [comment]
> Sorry I delete my comment, cause i indeed found your comment, on the commit, that reverted the functionality  so, what's next?

Not sure. I just downgraded with pip for now. See [above](https://github.com/Ulauncher/Ulauncher/issues/275#issuecomment-416039655).

I'm not the maintainer. Just trying to help out, but I guess the methods could be wrapped somehow (although this is what the ws library maintainer has been trying to do/fix for the last 5 releases so maybe it's not trivial), the ws-client could be fixed to 0.52.0 (meaning it can't be a global dependency like now). In the longer term it could be a good idea to replace it with something more stable, well tested and mature. Based on my impressions so far that could be anything ;)

**Comment by gornostal** [comment]
> Based on my impressions so far that could be anything ;)

:rofl: 

I've decided to make a workaround because I'm not sure when those breaking changes to WebSocketApp callbacks end.

**Comment by gornostal** [comment]
Fixed in 4.3.0

**Comment by dnome2** [comment]
I had 0.56.0 and I was still seeing the issue and as @friday mentioned I downgraded to 0.52.0 and still see the issue. Can someone please help, why I'm still seeing this issue?

**Comment by friday** [comment]
Which Ulauncher version are you using @dnome2? This was fixed a year ago.
