### ISSUE TITLE
ULauncher ALWAYS stops working after a few weeks of use

### ISSUE THREAD

**Issue by leirbag28** [Ulauncher/Ulauncher#467]
### Steps to reproduce
1. Install on Ubuntu 14.04, or 16.04 or 18.04 (all MATE desktop 32bit or 64bit)
2. Also install Kupfer
3. STart using ULauncher Regularly

### Current behavior
Doent work at all when I type ANY app or search nothing comes up a if it stopped thinking

### Expected behavior
TO show me 1 or more items/apps to open when I type its name

### Environment
**Ulauncher version**: 5.4 and 3 previous versions at least
**Linux distro**: Ubuntu MATE 14.04, 16.04 and 18.04 32bit and 64bit
**Desktop environment**: MATE

### Logs
 https://gist.github.com/leirbag28/e9e6c8f3956ad8575d546065ccb9bbf5

**Comment by gornostal** [comment]
@leirbag28 the link to the logs doesn't work for me.

Is Kupfer a required step to reproduce the bug?

**Comment by leirbag28** [comment]
Hi Aleksander
I don't know if Kupfer is required, but in theory I thinknit might be because I always install it along with ULauncher.

My theory is because maybe they both use the same type of
Search or more accurately maybe they conflict with each other and one ends up ruining the other? I don't know...it also happened when I has Synapse installed.

But maybe that doesnt matter at all and it is something else

I have never reported a bug through the method suggested...maybe I  an email you the output directly?

**Comment by gornostal** [comment]
Hi @leirbag28 
Sorry I disappeared for a few months. 

If you still have this issue, please reopen and attach a log. I'll try to help

**Comment by leirbag28** [comment]
Yes! The problem still exists...I updated to the latest version yesterday and still shows no results
Thank You for remembering! I occasionally remembered but dont have internet to have done it at that moment :-)

I will look at how to do the process again to send you the log

**Comment by leirbag28** [comment]
Here is the code I previously tried to send:


https://gist.github.com/leirbag28/e9e6c8f3956ad8575d546065ccb9bbf5#file-gistfile1-txt

**Comment by gornostal** [comment]
Thanks for the logs. It seems to be related to the issue that I just fixed.
I'm going to release a new version soon and post an update here

**Comment by gornostal** [comment]
Please try Ulauncher v5.6.0
The issue should be fixed there

**Comment by leirbag28** [comment]
Yeah I had immediatley recieved an email for issue #467 after your previous email...but unless you released anothe version of ULauncher today...the problem is still there because I downloaded the new version of ULauncher yesterday

**Comment by leirbag28** [comment]
Ok...I will try when I get home if thats not the version I already downloaded yesterday

**Comment by gornostal** [comment]
@leirbag28 yes, I've released a new version today

**Comment by leirbag28** [comment]
Ok Great! I will check it out! 
I Love Ulauncher 👍🏻😄👍🏻

**Comment by leirbag28** [comment]
Good News! ULauncher 5.6 is now working!
👏🏻👏🏻👏🏻

Awesome Aleksandr! Thank You!

**Comment by gornostal** [comment]
Good to know it's working for you :ok_hand:

**Comment by leirbag28** [comment]
Hello Aleksandr and Happy New Year! to you and your family..... and an ULTRA Thank you for the Super Awesome ULauncher.

as you know I previously emailed you about a problem with ULauncher Pre 5.6 version that you fixed. But since 5.6.1 there has been a problem Ive noticed on all versions after 5.6.1....that is all of them have a delay the first time you use it after boot up. 5.6.1 open instantly and works faster than all the newer versions also... I am currently on version 5.9.0 on Ubuntu 18.04.5 MATE 64 bit
on an Acer Chromebook C720p.

I will reinstall 5.6.1 back for now.     On Monday, January 6, 2020, 02:16:05 AM EST, Aleksandr Gornostal <notifications@github.com> wrote:  
 
 
Good to know it's working for you 👌

**Comment by gornostal** [comment]
Hi @leirbag28 

Sorry for the late reply.
I found some changes in 5.6.1 that may have affected the performance, but to confirm that could you please create a new issue and attach a log?

**Comment by leirbag28** [comment]
Ok...I will do that on one of my other systems...as I screwed up my personal laptop so bad and recovered mostly but now somehow it caused Ulauncher 5.6.1 to act like the recent versions in that on the first time opening it with CTRL + Space it reacts slow. Not sure if it is related to my Python 3 errors. But yeah I will send yo that info from another laptop I have with Ulauncher 5.6.1

**Comment by leirbag28** [comment]
Wait I just reread your email...to be clear, there is no error in ULauncher 5.6.1 .....the problem I have detected, is that every version above 5.6.1 (5.6.2 - 5.9? ) open slow to react on the first try. So what do you need me to do exactly? And if you need a log....a log from which version? Also how do you produce a log? I forgot how.

**Comment by gornostal** [comment]
@leirbag28 I understand that there's no error. I need a log because it has time stamps and there's a chance to figure out the source of the slow behavior by looking at the logs.
I'd like to see the log from any version of Ulauncher that works slow for you.
When you click on the "Submit an issue" button in Github you'll see a template, which will explain how to get that log.

**Comment by leirbag28** [comment]
I already submitted it as soon as I sent you that last email.
