### ISSUE TITLE
Excluding application search results

### ISSUE THREAD

**Issue by beskhu3epnm** [Ulauncher/Ulauncher#480]
## Question
Hi. I'm wondering how to exclude certain application results from showing in search. In particular, when I search for the Terminal, two identical applications with two identical descriptions and icons show up, the first result being the settings for the Terminal. I wish to exclude the first result.

Using v5.4.1 ~beta1

Also, this extension broke (https://ext.ulauncher.io/-/github-friday-ulauncher-clipboard) updating from v4 to the latest version. I submitted a bug report.

**Comment by friday** [comment]
The latter part has been fixed.

**Comment by gornostal** [comment]
@beskhu3epnm I think the following should work:

* find .desktop file of the app that you want to hide. Usually it's in `/usr/share/applications/`
* Copy it to `~/.local/share/applications/code.desktop`
* Edit it and add `Hidden=true`

**Comment by beskhu3epnm** [comment]
@gornostal I followed your instructions and the application still shows.

**Comment by gornostal** [comment]
@beskhu3epnm is the file name the same in both directories?

I've just tried, it works for me

**Comment by beskhu3epnm** [comment]
I'm sorry I forgot to respond. Restarting my computer allowed the change to take effect. Just required a reboot.

**Comment by gornostal** [comment]
It's good it works now.
BTW, It usually takes about 3-5 seconds for the changes to take effect.
