### ISSUE TITLE
Single quote not properly passed to $@ arguments in script shortcuts?

### ISSUE THREAD

**Issue by iago-lito** [Ulauncher/Ulauncher#984]
### Environment

$ uname -a -> Linux etak 5.16.11-arch1-1 #1 SMP PREEMPT Thu, 24 Feb 2022 02:18:20 +0000 x86_64 GNU/Linux

### Bug description

When the text after keyword contains single quotes, they are not automatically escaped before being passed to `$@` arguments.
For instance, create the following `dummy` shortcut with the following script:
```bash
#!/bin/bash
echo "$@" > ~/temp
```
- Type `dummy ab` to ulauncher output: the file is created and contains `ab`.
- Type `dummy a'b`: the file is not created (silent fail)
- Type `dummy a\'b`: the file is created with `a'b` (expected: `a\'b`)
- Type `dummy a'b'`: the file is created with `ab` (expected: `a'b'`) 

### Log output

```shell
When failing with `dummy a'b`, the output contains the following:

/bin/sh: -c: line 1: unexpected EOF while looking for matching `''
/bin/sh: -c: line 2: syntax error: unexpected end of file
```

### Communication guidelines

- [X] I have read and agree with Ulauncher's communication guidelines.

### Not an extension issue

- [X] This issue applies to the Ulauncher application, not a specific extension.

### Latest version

- [X] I am using the latest Ulauncher release.

**Comment by friday** [comment]
I can't even remember if this is fixed in v6 at this point. Waiting for one more large feature to be implemented before we can switch over to that branch.

**Comment by iago-lito** [comment]
Okay, cheers :) Are you meaning that the problem will likely disappear once you are done switching?

**Comment by friday** [comment]
No. I just have no time and wanted to acknowledge that we have seen your report.

**Comment by friday** [comment]
I don't know which distro you are on, but v6 is the main branch now and the AUR (arch) package `ulauncher-git` uses it.

d2c42b65507424eba8086c57cbcec06f8b2850d3 might have fixed this as it did fix an issue with shortcut arguments, but there are still issues with how these scripts are ran, that makes me want to rewrite this completely. I think it's inefficient to create a temporary script file every time you execute these anyway (better to store the shortcuts directly as executable scripts or to eval them imo). I haven't been able to allocate enough time to look into this though. If you would have the time to test and help it would be greatly appreciated, although just filing the issue is a contribution already :)

**Comment by friday** [comment]
I really should have read your issue more closely. There's no $@ argument. It's $s.

It says this in the shortcut preferences .

Maybe $@ worked in v5, but the documented way to do it was always $s. It's a simple string replace.

https://github.com/Ulauncher/Ulauncher/blob/1b66c7636ae8614ab880db7eda6b3e5d718a3fbc/ulauncher/modes/shortcuts/ShortcutResult.py#L57

**Comment by friday** [comment]
I just found this comment, indicating %s was actually never intended to work for the shell arguments while actual shell argument code did:
https://github.com/Ulauncher/Ulauncher/blob/fe9f613a8764cd0ef2a8d1fe6ab205895e460b2a/preferences-src/src/components/pages/EditShortcut.vue#L33

So this is either a regression, or breaking change. I see no reason to remove support for shell arguments though, so I'll try to get those working also. You can use $s in the meanwhile.

**Comment by iago-lito** [comment]
I'm currently hitting #114 :( But I'll try `$s` as soon as I get my system up to date and can edit my scripts again.

**Comment by friday** [comment]
Fixed in aabe254b77f7db88b5180168eeb698f1d0f6b7e4, and the issue you mentioned above is fixed also for Arch users who were getting it recently ^

You can also see the stdout from shortcut scripts now if you run ulauncher in verbose mode (`-v` cli flag) which should help debugging them c0eff5e1b7ae50d5697bc41c569adccb8a7dffa1

**Comment by bitboss-ca** [comment]
This is still an issue on Ubuntu 24.04 today in 2026.  I am using Ulauncher 5.15.15 and entering a single quote in Ulauncher results in a silent failure.  Cannot access what was typed in the search field, not using $@, or $s or %s
